version:    2
jobs:
  one:
    docker:
      - image: armhf/alpine:latest
      - entrypoint: /usr/sbin/mosquitto
    steps:
      - checkout
      - run: apk update
      - run: apk upgrade
      - run: apk --no-cache add mosquitto mosquitto-clients
workflows:
  version:  2
  all_jobs:
    jobs:
      - one
