version: 2
jobs:
  build:
    docker:
      - image: danclegg/alpine-armhf-rpi-gpio:$CIRCLE_SHA1 .
    steps:
      - checkout
      - run: apk update
      - run: apk upgrade
      - run: apk --no-cache add mosquitto mosquitto-clients
      - attach_workspace:
        - at: /usr/sbin/mosquitto
  build:
    docker:
      - image: danclegg/alpine-armhf-rpi-gpio:latest .
    steps:
      - checkout
      - run: apk update
      - run: apk upgrade
      - run: apk --no-cache add mosquitto mosquitto-clients
      - attach_workspace:
        - at: /usr/sbin/mosquitto

