version: 2
jobs:
  build:
    docker:
      - image: armhf/alpine:latest
      - entrypoint: /usr/sbin/mosquitto
    steps:
      - checkout
      - run: apk update
      - run: apk upgrade
      - run: apk --no-cache add mosquitto mosquitto-clients
